# Generated by Django 3.1.7 on 2021-04-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news0', '0002_auto_20210407_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
    ]
